project:
  type: website
  
execute:
  freeze: auto

website:
  title: "Shiny tools for management rules -- SMM 2022"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Slides"
        menu:
        #day 1am
          - Overview_of_workshop.qmd #1
          - text: "2a. Apps in action-NERW" #2a
            href: Apps_in_action-NERW.pdf
          - text: "2b. Apps in Action-WhaleMap" #2b
            href: Apps_in_action-WhaleMap.pdf 
          - Group_discussion-day1_am.qmd #3
        #day 1pm
          - Intro_to_shiny.qmd #4
          - Shiny_tours-NERW.qmd #5a
          - Shiny_tours-WhaleMap.qmd #5b
          - Group_discussion-day1_pm.qmd #6
          
        #day 2am
          - Overview_of_day.qmd #7
          - Shiny_skill_building.qmd #8
          - Simplified_app.qmd #9
        #day 2pm
          - Documenting.qmd #10
          - Deployment.qmd #11
          - Group_discussion-day2_pm.qmd #12
        
      - text: "Recordings"
        menu: 
          - text: "1. Overview of workshop"
            href: https://youtu.be/_KV6FNSGvaI
          - text: "2a. Apps in action-NERW"
            href: https://youtu.be/wN_2-YtpQAY
          - text: "2b. Apps in action-WhaleMap"
            href: https://youtu.be/7hWXi_UU_K0
          - text: "5a. Shiny tours-NERW"
            href: https://youtu.be/3JfL4f2tm9I
          - text: "5b. Shiny tours-WhaleMap"
            href: https://youtu.be/0ap0YN1gGxA
          - text: "9. Simplified app"
            href: https://youtu.be/KHexyVIk92s
          - text: "10. Documenting"
            href: https://youtu.be/8dbH8YaOtQA
          - text: "11. Deployment"
            href: https://youtu.be/oLURRdvojBY
          - text: "12. Discussion"
            href: https://youtu.be/vIvKjo9znz8

format:
  html:
    theme: minty
    css: styles.css
    toc: true



