project:
  type: website
  
execute:
  freeze: auto

website:
  title: "Shiny tools for management rules -- SMM 2022"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Slides"
        menu:
        #day 1am
          - Overview_of_workshop.qmd #1
          - text: "2a. Apps in action-NERW" #2a
            href: Apps_in_action-NERW.pdf
          - text: "2b. Apps in Action-WhaleMap" #2b
            href: Apps_in_action-WhaleMap.pdf 
          - Group_discussion-day1_am.qmd #3
        #day 1pm
          - Intro_to_shiny.qmd #4
          - Shiny_tours-NERW.qmd #5a
          - Shiny_tours-WhaleMap.qmd #5b
          - Group_discussion-day1_pm.qmd #6
          
        #day 2am
          - Overview_of_day.qmd #7
          - Shiny_skill_building.qmd #8
          - Simplified_app.qmd #9
        #day 2pm
          - Documenting.qmd #10
          - Deployment.qmd #11
          - Group_discussion-day2_pm.qmd #12
        
      - text: "Recordings"
        menu: 
          - text: "1. Overview of workshop"
          - text: "2a. Apps in action-NERW"
          - text: "2b. Apps in action-WhaleMap"

format:
  html:
    theme: minty
    css: styles.css
    toc: true



